[theme]
primaryColor = "#ff00ff"        # ton rose Lexyo
backgroundColor = "#ffffff"     # blanc
secondaryBackgroundColor = "#f5f5f5"  # gris clair (facultatif)
textColor = "#000000"           # noir
font = "sans serif"             # propre et moderne
